# Generated by Django 5.2.17 on 2026-09-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='사업명')),
                ('bid_no', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='공고번호')),
                ('org', models.CharField(blank=True, max_length=200, verbose_name='공고기관')),
                ('item_name', models.CharField(blank=True, max_length=200, verbose_name='구매품목')),
                ('quantity', models.CharField(blank=True, max_length=50, verbose_name='수량')),
                ('estimated_price', models.CharField(blank=True, max_length=100, verbose_name='추정가격')),
                ('delivery_place', models.CharField(blank=True, max_length=300, verbose_name='납품장소')),
                ('delivery_term', models.CharField(blank=True, max_length=200, verbose_name='납품기한')),
                ('announced_on', models.DateField(blank=True, null=True, verbose_name='공고일')),
                ('inquiry_due_at', models.DateTimeField(blank=True, null=True, verbose_name='기술질의 접수마감')),
                ('bid_due_at', models.DateTimeField(blank=True, null=True, verbose_name='입찰서 제출마감')),
                ('opening_at', models.DateTimeField(blank=True, null=True, verbose_name='개찰')),
                ('spec_doc_no', models.CharField(blank=True, max_length=100, verbose_name='사양서 문서번호')),
                ('notes', models.TextField(blank=True, verbose_name='기타 사항')),
            ],
            options={
                'verbose_name': '입찰 건',
                'verbose_name_plural': '입찰 건',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.CharField(max_length=20, verbose_name='연번')),
                ('text', models.TextField(verbose_name='자격 요건')),
                ('status', models.CharField(choices=[('have', '보유'), ('need', '발급 필요'), ('uncertain', '확인 필요')], default='uncertain', max_length=20, verbose_name='자사 상태')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_reqs', to='projects.bidproject')),
            ],
            options={
                'verbose_name': '입찰 참가자격',
                'verbose_name_plural': '입찰 참가자격',
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('project', 'seq'), name='uniq_participation_per_project')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.IntegerField(verbose_name='연번')),
                ('name', models.CharField(max_length=200, verbose_name='서류명')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='공고 비고')),
                ('status', models.CharField(choices=[('have', '보유'), ('need', '발급 필요'), ('uncertain', '확인 필요')], default='uncertain', max_length=20, verbose_name='자사 상태')),
                ('evidence_text', models.TextField(blank=True, verbose_name='매핑 근거')),
                ('is_checked', models.BooleanField(default=False, verbose_name='확인')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_items', to='projects.bidproject')),
            ],
            options={
                'verbose_name': '제출서류',
                'verbose_name_plural': '제출서류',
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('project', 'seq'), name='uniq_submission_seq_per_project')],
            },
        ),
    ]
