# Generated by Django 5.2.17 on 2026-09-28 08:53

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Both extensions must exist before the operations that use them:
        # VectorField needs `vector`, and the kchunk_content_trgm index needs
        # `pg_trgm` for gin_trgm_ops (specs/03-data-model.md section 0).
        #
        # db_init.sql already creates them; these are idempotent (CREATE
        # EXTENSION IF NOT EXISTS) and make the migration self-sufficient on a
        # fresh database. They need a superuser, so on a locked-down cluster run
        # db_init.sql first and these become no-ops.
        VectorExtension(),
        TrigramExtension(),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('doc_no', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='문서번호')),
                ('doc_kind', models.CharField(choices=[('catalog', '제품카탈로그'), ('qa', '인증·시험·실적'), ('other', '기타')], max_length=20, verbose_name='종류')),
                ('file', models.FileField(upload_to='knowledge/', verbose_name='파일')),
                ('revision_date', models.DateField(blank=True, null=True, verbose_name='개정일/기준일')),
                ('status', models.CharField(choices=[('uploaded', '업로드됨'), ('parsing', '추출중'), ('parsed', '추출완료'), ('indexing', '색인중'), ('indexed', '색인완료'), ('failed', '실패')], default='uploaded', max_length=20, verbose_name='상태')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='청크 수')),
                ('embedding_model', models.CharField(blank=True, max_length=100, verbose_name='임베딩 모델')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 사유')),
            ],
            options={
                'verbose_name': '지식 문서',
                'verbose_name_plural': '지식 문서',
                'ordering': ['doc_kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_parent', models.BooleanField(default=False, verbose_name='부모 청크')),
                ('content', models.TextField(verbose_name='내용')),
                ('section_path', models.CharField(blank=True, max_length=300, verbose_name='절 경로')),
                ('heading', models.CharField(blank=True, max_length=300, verbose_name='헤딩')),
                ('page_no', models.IntegerField(blank=True, null=True, verbose_name='페이지')),
                ('chunk_type', models.CharField(choices=[('table', '표 전체'), ('table_row', '표 행'), ('text', '본문'), ('heading', '헤딩')], default='text', max_length=20, verbose_name='청크 종류')),
                ('token_count', models.IntegerField(default=0, verbose_name='토큰 수')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='임베딩')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None, verbose_name='정확 매칭 토큰')),
                ('model_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None, verbose_name='제품 모델 태그')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.knowledgechunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'verbose_name': '지식 청크',
                'verbose_name_plural': '지식 청크',
                'ordering': ['document_id', 'id'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='kchunk_embedding_hnsw', opclasses=['vector_cosine_ops']), django.contrib.postgres.indexes.GinIndex(fields=['content'], name='kchunk_content_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='kchunk_keywords_gin'), django.contrib.postgres.indexes.GinIndex(fields=['model_tags'], name='kchunk_model_tags_gin'), models.Index(fields=['document', 'is_parent'], name='knowledge_k_documen_cfeb19_idx')],
            },
        ),
    ]
