# Generated by Django 5.2.17 on 2026-09-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('knowledge', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', '대기'), ('running', '진행중'), ('done', '완료'), ('failed', '실패')], default='queued', max_length=20, verbose_name='상태')),
                ('current_step', models.CharField(blank=True, max_length=100, verbose_name='진행 단계')),
                ('total_count', models.IntegerField(default=0, verbose_name='전체 항목 수')),
                ('processed_count', models.IntegerField(default=0, verbose_name='처리한 항목 수')),
                ('llm_model', models.CharField(blank=True, max_length=100, verbose_name='LLM 모델')),
                ('embedding_model', models.CharField(blank=True, max_length=100, verbose_name='임베딩 모델')),
                ('rag_params', models.JSONField(default=dict, verbose_name='RAG 파라미터')),
                ('prompt_versions', models.JSONField(default=dict, verbose_name='프롬프트 버전')),
                ('llm_calls', models.JSONField(default=list, verbose_name='LLM 호출 기록')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 사유')),
                ('summary', models.JSONField(default=dict, verbose_name='판정 요약')),
                ('accuracy', models.JSONField(blank=True, null=True, verbose_name='정확도')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='projects.bidproject')),
            ],
            options={
                'verbose_name': '분석 실행',
                'verbose_name_plural': '분석 실행',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verdict', models.CharField(choices=[('MEET', '충족'), ('GAP', '보완 필요'), ('CHECK', '확인 필요')], max_length=10, verbose_name='판정')),
                ('ai_verdict', models.CharField(choices=[('MEET', '충족'), ('GAP', '보완 필요'), ('CHECK', '확인 필요')], max_length=10, verbose_name='AI 판정')),
                ('evidence_state', models.CharField(choices=[('found_sufficient', '근거 확인, 충족'), ('found_insufficient', '근거 확인, 미달'), ('found_absent', '자사 자료에 미보유 명시'), ('not_found', '근거 검색 실패')], default='not_found', max_length=20, verbose_name='근거 상태')),
                ('our_value', models.CharField(blank=True, max_length=300, verbose_name='자사값')),
                ('ai_our_value', models.CharField(blank=True, max_length=300, verbose_name='AI 자사값')),
                ('rationale', models.TextField(blank=True, verbose_name='판정 사유')),
                ('gap_detail', models.TextField(blank=True, verbose_name='미달 내용')),
                ('remedy', models.TextField(blank=True, verbose_name='대체방안')),
                ('remedy_side_effects', models.JSONField(default=list, verbose_name='대체방안 부작용')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='확신도')),
                ('retrieval_query', models.TextField(blank=True, verbose_name='검색 쿼리')),
                ('retrieved_chunk_ids', models.JSONField(default=list, verbose_name='검색된 청크')),
                ('is_edited', models.BooleanField(default=False, verbose_name='사용자 수정')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='수정 시각')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='documents.requirement')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='analysis.analysisrun')),
            ],
            options={
                'verbose_name': '판정',
                'verbose_name_plural': '판정',
                'ordering': ['requirement__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CrossClauseIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_nos', models.JSONField(default=list, verbose_name='관련 조항')),
                ('kind', models.CharField(choices=[('option_side_effect', '선택사양 부작용'), ('mutually_exclusive', '동시 만족 불가'), ('other', '기타')], default='other', max_length=40, verbose_name='종류')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('severity', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=20, verbose_name='심각도')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='무시')),
                ('requirements', models.ManyToManyField(blank=True, related_name='cross_issues', to='documents.requirement')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_issues', to='analysis.analysisrun')),
            ],
            options={
                'verbose_name': '교차조항 이슈',
                'verbose_name_plural': '교차조항 이슈',
                'ordering': ['severity', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_title', models.CharField(max_length=300, verbose_name='근거 문서')),
                ('doc_no', models.CharField(blank=True, max_length=100, verbose_name='문서번호')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='위치')),
                ('page_no', models.IntegerField(blank=True, null=True, verbose_name='페이지')),
                ('quote', models.TextField(blank=True, verbose_name='인용')),
                ('parent_content', models.TextField(blank=True, verbose_name='부모 청크 전문')),
                ('score', models.FloatField(default=0.0, verbose_name='결합 점수')),
                ('semantic_score', models.FloatField(blank=True, null=True, verbose_name='의미 점수')),
                ('keyword_score', models.FloatField(blank=True, null=True, verbose_name='키워드 점수')),
                ('rank', models.IntegerField(default=1, verbose_name='순위')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='analysis.assessment')),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='knowledge.knowledgechunk')),
            ],
            options={
                'verbose_name': '근거',
                'verbose_name_plural': '근거',
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('xlsx', 'Excel'), ('markdown', 'Markdown 보고서')], max_length=20, verbose_name='종류')),
                ('file', models.FileField(upload_to='exports/%Y/%m/', verbose_name='파일')),
                ('filename', models.CharField(max_length=300, verbose_name='파일명')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='analysis.analysisrun')),
            ],
            options={
                'verbose_name': '산출물 파일',
                'verbose_name_plural': '산출물 파일',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.IntegerField(verbose_name='순번')),
                ('clause_refs', models.JSONField(default=list, verbose_name='관련 조항')),
                ('source_kind', models.CharField(choices=[('check', '확인 필요 항목'), ('gap_remedy', '대체방안 승인 요청'), ('cross_clause', '교차조항 상충')], max_length=20, verbose_name='후보 출처')),
                ('body', models.TextField(verbose_name='문안')),
                ('ai_body', models.TextField(blank=True, verbose_name='AI 원본 문안')),
                ('is_included', models.BooleanField(default=True, verbose_name='포함')),
                ('is_edited', models.BooleanField(default=False, verbose_name='사용자 수정')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='analysis.analysisrun')),
            ],
            options={
                'verbose_name': '기술질의 초안',
                'verbose_name_plural': '기술질의 초안',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['project', 'status'], name='analysis_an_project_5ec63f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['run', 'verdict'], name='analysis_as_run_id_9f1e39_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('run', 'requirement'), name='uniq_assessment_per_run'),
        ),
    ]
