# Generated by Django 5.2.17 on 2026-09-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('announcement', '입찰공고문'), ('techspec', '기술사양서')], max_length=20, verbose_name='문서 종류')),
                ('file', models.FileField(upload_to='bids/%Y/%m/', verbose_name='파일')),
                ('original_name', models.CharField(max_length=300, verbose_name='원본 파일명')),
                ('doc_no', models.CharField(blank=True, max_length=100, verbose_name='문서번호')),
                ('page_count', models.IntegerField(default=0, verbose_name='페이지 수')),
                ('status', models.CharField(choices=[('uploaded', '업로드됨'), ('parsing', '추출중'), ('parsed', '추출완료'), ('indexing', '색인중'), ('indexed', '색인완료'), ('failed', '실패')], default='uploaded', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 사유')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.bidproject')),
            ],
            options={
                'verbose_name': '입력 문서',
                'verbose_name_plural': '입력 문서',
                'ordering': ['doc_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_no', models.CharField(max_length=30, verbose_name='조항')),
                ('chapter', models.CharField(blank=True, max_length=100, verbose_name='구분')),
                ('category', models.CharField(choices=[('dimension', '제품 치수'), ('filter_grade', '등급'), ('efficiency', '효율'), ('pressure_drop', '차압'), ('test_standard', '시험규격'), ('certification', '인증'), ('delivery', '납기'), ('submission', '제출서류'), ('performance', '성능'), ('material', '재질·구조'), ('track_record', '실적'), ('other', '기타')], default='other', max_length=20, verbose_name='분류')),
                ('item', models.CharField(max_length=200, verbose_name='항목')),
                ('requirement_text', models.TextField(blank=True, verbose_name='요구조건')),
                ('context_text', models.TextField(blank=True, verbose_name='관련 서술')),
                ('source_page', models.IntegerField(blank=True, null=True, verbose_name='출처 페이지')),
                ('order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='분석 대상')),
                ('is_graded', models.BooleanField(default=False, verbose_name='채점 대상')),
                ('is_edited', models.BooleanField(default=False, verbose_name='사용자 수정')),
                ('ai_item', models.CharField(blank=True, max_length=200)),
                ('ai_requirement_text', models.TextField(blank=True)),
                ('ai_category', models.CharField(blank=True, max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.bidproject')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='documents.sourcedocument')),
            ],
            options={
                'verbose_name': '요구사항',
                'verbose_name_plural': '요구사항',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='documents_r_project_11f2d4_idx'), models.Index(fields=['project', 'is_graded'], name='documents_r_project_e532b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'clause_no', 'item'), name='uniq_requirement_per_project')],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_no', models.IntegerField(verbose_name='페이지 번호')),
                ('text', models.TextField(blank=True, verbose_name='표 밖 본문')),
                ('tables', models.JSONField(default=list, verbose_name='표')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.sourcedocument')),
            ],
            options={
                'verbose_name': '문서 페이지',
                'verbose_name_plural': '문서 페이지',
                'ordering': ['page_no'],
                'constraints': [models.UniqueConstraint(fields=('document', 'page_no'), name='uniq_page_per_document')],
            },
        ),
    ]
